import type { NextPage, GetStaticProps } from 'next'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


interface Todo {
  userId: number,
  id: number,
  title: string,
  completed: boolean
}

interface User {
  id: number,
  name: string,
  username: string,
  email: string,
  phone: string
  website: string
  company: { name: string, catchPhrase: string, bs: string }
  address: {
    street: string,
    suite: string,
    city: string,
    zipcode: string,
    geo: { lat: number, lng: number }
  }
}


const UserCard: NextPage<{ user: User }> = ({ user }) => {
  return <div className="w-full">{user.name}</div>

}

const TodoCard: NextPage<{ todo: Todo }> = ({ todo }) => {
  return <div className="w-full">
    <li>{todo.id}</li>
    <li>{todo.completed}</li>
    <li>{todo.title}</li>
  </div>

}

const Home: NextPage<{ users: User[], todos: Todo[] }> = ({ users, todos }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>



      <main className={styles.main}>
        <div className="columns-3">
          {users.map(u => <UserCard key={u.id} user={u} />)}
        </div>
        <div className="columns-3">
          {todos.map(t => <TodoCard key={t.id} todo={t} />)}
        </div>
      </main>

    </div>
  )
}

export default Home


export const getStaticProps: GetStaticProps = async () => {
  const todos: Todo[] = await (await fetch('https://jsonplaceholder.typicode.com/todos')).json()
  const users: User[] = await (await fetch('https://jsonplaceholder.typicode.com/users')).json()


  return {
    props: {
      users,
      todos
    }
  }
}
